version: '3'
services:
  docker_dns:
    build: docker_dns
    restart: always
    ports:
      - "5301:53/udp"
      - "5301:53/tcp"
      - "10001:10000/tcp"

    stdin_open: true
    tty: true
    privileged: true
    user: root
    container_name: docker_dns
    hostname: ghkdtlwns987
    volumes:
      - ./docker_dns/etc/resolv.conf:/etc/resolv.conf
      - ./docker_dns/etc/named.conf.options:/etc/bind/named.conf.options
      - ./docker_dns/etc/named.conf.local:/etc/bind/named.conf.local
      - ./docker_dns/etc/ghkdtlwns987.com.zone:/var/cache/bind/ghkdtlwns987.com.zone
      - ./docker_dns/etc/ghkdtlwns987.com.zone.rev:/var/cache/bind/ghkdtlwns987.com.zone.rev
    networks:
      docker_practice_mynet:
        ipv4_address: 172.28.0.2

  docker_web1:
    build: docker_web1
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    user: root
    container_name: docker_web1
    ports:
      - "11111:80"
    networks:
      docker_practice_mynet:
        ipv4_address: 172.28.0.3

networks:
  docker_practice_mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

